# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      deployments: write
      pages: write

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.DEPLOY_KEY}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: Install modules and push to gh-pages
        run: |
          # abort on errors
          set -e
          
          # install node_modules
          npm ci

          # build
          npm run build

          # Set git user
          git config --local user.name Jeffrey-Meesters
          git config --local user.email jjeffreymeesters@gmail.com

          # navigate into the build output directory
          echo build done, checking out dist
          cd dist
          
          git init
          git checkout -b main
          git add -A
          git commit -m 'deploy'

          echo deploying to gh-pages
          # if you are deploying to https://<USERNAME>.github.io/<REPO>
          git push -f https://Jeffrey-Meesters:${{secrets.DEPLOY_KEY}}@github.com/Jeffrey-Meesters/jeffrle main:gh-pages

          cd -